In [1]:
import numpy as np

1.

In [8]:
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('multi_array.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2)

In [9]:
npzfile = np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [10]:
print(npzfile['array1'])
print(npzfile['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


2.

In [12]:
array3 = np.array([[4,5,6],[1,2,3]])
with open('multi_array2.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2, array3=array3)

In [13]:
npzfile = np.load('multi_array2.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [14]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
